import { getActionLabel } from "@/lib/i18n-utils"
import { getLocalKeyWithHost } from "@/lib/utils"
import { QueryListPayloadType } from "@/models"

export const LOCAL_STORE_KEYS = {
  USER: getLocalKeyWithHost("USER"),
  ROLES: getLocalKeyWithHost("ROLES"),
}

export const TOKEN_KEY = getLocalKeyWithHost("TOKEN")

export const QUERY = {
  COMPANY: "COMPANY",
  USERS: "FETCH_USERS",
  PERMISSIONS: "FETCH_PERMISSIONS",
  PERMISSIONS_BY_USER: "FETCH_PERMISSIONS_BY_USER",
  PERMISSION_GROUPS: "PERMISSION_GROUPS",
  LANGUAGES: "LANGUAGES",
  NEWS_CATEGORIES: "NEWS_CATEGORIES",
  BRANCHES: "BRANCHES",
  BANNERS: "BANNERS",
  MENUS: "MENUS",
  WHO_WE_ARE: "WHO_WE_ARE",
  PAGE_HOME: "PAGE_HOME",
  PAGE_HOME_SOFT: "PAGE_HOME_SOFT",
  PROJECT_CATEGORIES: "PROJECT_CATEGORIES",
  SOFT_CATEGORIES: "SOFT_CATEGORIES",
  TYPE_SOFT: "TYPE_SOFT",
  FAQS: "FAQS",
  FAQS_CATEGORY: "FAQS_CATEGORY",
  CONFIG_FOOTER: "CONFIG_FOOTER",
  POSTS: "POSTS",
  CUSTOMER_FEEDBACKS: "CUSTOMER_FEEDBACKS",
  GUIDELINES: "GUIDELINES",
  GUIDELINE_CONTENTS: "GUIDELINE_CONTENTS",
  GUIDELINE_VIDEOS: "GUIDELINE_VIDEOS",
  CARDS: "CARDS",
  CARD_CATEGORY: "CARD_CATEGORY",
  CONFIG: "CONFIG",
  INTRODUCE: "INTRODUCE",
  CONFIG_FOOTER_CATEGORY: "CONFIG_FOOTER_CATEGORY",
  AGENT_REGISTER: "AGENT_REGISTER",
  PRICE: "PRICE",
  PLATFORM_CATEGORY: "PLATFORM_CATEGORY",
  PROJECT: "PROJECT",
  SOCIAL_MEDIA_ICON: "SOCIAL_MEDIA_ICON",
  SOCIAL_MEDIA_LINK: "SOCIAL_MEDIA_LINK",
  CUSTOMER_CONTACTS: "CUSTOMER_CONTACTS",
  SERVICE_CATEGORIES: "SERVICE_CATEGORIES",
}

export const MUTATE = {
  LOGIN: "LOGIN",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  USER: "MUTATE_USER",
  DELETE_USER: "DELETE_USER",
  PERMISSION: "MUTATE_USER_PERMISSION",
  UPLOAD_FILE: "UPLOAD_FILE",
  PERMISSION_GROUP: "PERMISSION_GROUP",
  DELETE_PERMISSION_GROUP: "DELETE_PERMISSION_GROUP",
  LANGUAGE: "LANGUAGE",
  NEWS_CATEGORY: "NEWS_CATEGORY",
  DELETE_NEWS_CATEGORY: "DELETE_NEWS_CATEGORY",
  BRANCH: "BRANCH",
  DELETE_BRANCH: "DELETE_BRANCH",
  BANNER: "BANNER",
  DELETE_BANNER: "BANNER",
  MENU: "MENU",
  DELETE_MENU: "DELETE_MENU",
  WHO_WE_ARE: "WHO_WE_ARE",
  DELETE_WHO_WE_ARE: "DELETE_WHO_WE_ARE",
  PROJECT_CATEGORY: "PROJECT_CATEGORY",
  DELETE_PROJECT_CATEGORY: "DELETE_PROJECT_CATEGORY",
  SOFT_CATEGORY: "SOFT_CATEGORY",
  DELETE_SOFT_CATEGORY: "DELETE_SOFT_CATEGORY",
  FAQS: "FAQS",
  DELETE_FAQS: "DELETE_FAQS",
  CONFIG_FOOTER: "CONFIG_FOOTER",
  DELETE_CONFIG_FOOTER: "DELETE_CONFIG_FOOTER",
  POST: "POST",
  DELETE_POST: "DELETE_POST",
  CUSTOMER_FEEDBACK: "CUSTOMER_FEEDBACK",
  DELETE_CUSTOMER_FEEDBACK: "DELETE_CUSTOMER_FEEDBACK",
  GUIDELINE: "GUIDELINE",
  DELETE_GUIDELINE: "GUIDELINE",
  DELETE_GUIDELINE_CONTENT: "DELETE_GUIDELINE_CONTENT",
  GUIDELINE_CONTENT: "GUIDELINE_CONTENT",
  DELETE_GUIDELINE_VIDEO: "DELETE_GUIDELINE_VIDEO",
  GUIDELINE_VIDEO: "GUIDELINE_VIDEO",
  CARD: "CARD",
  DELETE_CARD: "DELETE_CARD",
  CONFIG: "CONFIG",
  DELETE_CONFIG: "DELETE_CONFIG",
  INTRODUCE: "INTRODUCE",
  DELETE_INTRODUCE: "DELETE_INTRODUCE",
  PAGE_HOME: "PAGE_HOME",
  DELETE_PAGE_HOME: "DELETE_PAGE_HOME",
  PAGE_HOME_SOFT: "PAGE_HOME_SOFT",
  DELETE_PAGE_HOME_SOFT: "DELETE_PAGE_HOME_SOFT",
  AGENT_REGISTER: "AGENT_REGISTER",
  DELETE_AGENT_REGISTER: "DELETE_AGENT_REGISTER",
  DELETE_PRICE: "DELETE_PRICE",
  PRICE: "PRICE",
  PROJECT: "PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  SOCIAL_MEDIA_LINK: "SOCIAL_MEDIA_LINK",
  DELETE_SOCIAL_MEDIA_LINK: "DELETE_SOCIAL_MEDIA_LINK",
  SOCIAL_MEDIA_ICON: "SOCIAL_MEDIA_ICON",
  DELETE_SOCIAL_MEDIA_ICON: "DELETE_SOCIAL_MEDIA_ICON",
  DELETE_CUSTOMER_CONTACT: "DELETE_CUSTOMER_CONTACT",
  CUSTOMER_CONTACT: "CUSTOMER_CONTACT",
}

export const TABLE = {
  COLUMN: "COLUMN",
}

export const ERROR_TYPES = {
  EMPTY: "empty",
  QUANTITY: "quantity",
}

export const PATHS = {
  POSTS: "/posts",
  GUIDELINE_VIDEO: "/guideline-videos",
  PROJECT: "/project",
  SOFTWARE_CATEGORY: "/software-category",
  PRICE: "/price",
  CUSTOMER_FEEDBACK: "/customer-feedbacks",
  INTRODUCE: "/introduce",
  SOCIAL_MEDIA_ICON: "/social-media-icon",
  CONFIG: "/config",
  PAGE_HOME: "/page-home",
  PAGE_HOME_SOFT: "/page-home-soft",
  MENU: "/menus",
  BANNER: "/banners",
  CARD: "/card",
}

export const DEFAULT_QUERY_LIST_PAYLOAD: QueryListPayloadType = {
  pageIndex: 1,
  pageSize: 1000,
  sortColumn: "Id",
  sortOrder: 1,
  filterColumn: [],
}

export const [
  saveLabel,
  createLabel,
  updateLabel,
  editLabel,
  deleteLabel,
  copyLabel,
  backLabel,
  closeLabel,
  selectLabel,
  enterLabel,
  cancelLabel,
  continueLabel,
  searchLabel,
  importLabel,
  exportLabel,
  okLabel,
  scanLabel,
  applyLabel,
  addLabel,
] = getActionLabel([
  "save",
  "create",
  "update",
  "edit",
  "delete",
  "copy",
  "back",
  "close",
  "select",
  "enter",
  "cancel",
  "continue",
  "search",
  "import",
  "export",
  "ok",
  "scan",
  "apply",
  "add",
])

export const FORMAT_DATE = "dd/MM/yyyy"
export const FORMAT_DATE_TIME = "dd/MM/yyyy HH:mm"
export const FILTER_DATE = "yyyyMMdd"
export const WIDTH_MD = 768
export const ZOOM_MAP_DEFAULT = 15
export const COORDINATE_DECIMAL_SCALE = 14
export const HOST = "phanmemviet.com.vn"
export const DEFAULT_LANG = "vi-VN"
